name: workflow exercicio 2

on:
  push:
   
jobs:
   checkout_code:
    name: verificacao
    runs-on: ubuntu-latest
   
    steps:
      - name: checkout repositorio
        uses: actions/checkout@v3.3.0
      - name: upload artefato
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ vars.NOME }}
          path: .
