name: workflow

on:
  push:
  
env:
  VARIAVEL_1: Rodrigo Yudi
  VARIAVEL_2: São Paulo
  
jobs:
  
  checkout_code:
    Name: Verificação do codigo
    runs-on ubuntu-latest
    env:
      VARIAVEL_JOB: 33

  steps:
  - name: Checkout repositorio
  uses: actions/checkout@v3.3.0
  
  -name: Upload a Build Artifact
  uses: actions/upload-artifact@v3.1.2
  with:
    name: ${{ vars.NOME }}
    path: .
