name: Imprime data atual

on:
  push:
  
jobs:
  imprime_data_ubuntu:
    name: Imprime data atual - Job 1
    runs-on: ubuntu-latest
    
    steps:
      - name: Imprime data atual
        run: date
  
  imprime_data_windows:
    name: Imprime data atual - Job 2
    runs-on: windows-latest
      
    steps:
      - name: Imprime data atual
        run: date   
        
  imprime_data_macos:
    name: Imprime data atual - Job 3
    runs-on: macos-latest
        
    steps:
      - name: Imprime data atual
        run: date        

  imprime_data_:
    name: Imprime data atual - Job 4
    runs-on: windows-latest
    needs:
      - imprime_data_ubuntu
      - imprime_data_windows
      - imprime_data_macos
    
    steps:
      - name: Imprime data atual
        run: date  
